#!/usr/bin/env python3

""" 
extract-and-align-cpsG-seqs.py by Rohan Maddamsetti
Extract manB and cpsG sequences from
the E. coli REL606 genome for this experiment (REL606.gff3),
write DNA and protein FASTA files and produce a MAFFT protein multiple sequence alignment.
Three sequences are extracted: (1) full manB CDS, (2) full cpsG CDS, and (3) a
chimeric sequence generated by a Δ23,293 bp deletion starting at position 2031703.
"""

import io
import subprocess
import tempfile
from pathlib import Path
from Bio import SeqIO
from Bio.SeqRecord import SeqRecord


def parse_gff3_and_fasta(gff3_path):
    annotation_lines = []
    fasta_lines = []
    in_fasta = False
    with open(gff3_path) as fh:
        for line in fh:
            if line.startswith("##FASTA"):
                in_fasta = True
                continue
            if in_fasta:
                fasta_lines.append(line)
            else:
                annotation_lines.append(line)

    genome = SeqIO.read(io.StringIO("".join(fasta_lines)), "fasta")

    features = []
    for line in annotation_lines:
        if line.startswith("#") or not line.strip():
            continue
        parts = line.rstrip("\n").split("\t")
        if len(parts) < 9:
            continue
        feat_type = parts[2]
        start = int(parts[3])
        end = int(parts[4])
        strand = parts[6]
        attrs = {k: v for k, v in (
            kv.split("=", 1) for kv in parts[8].split(";") if "=" in kv
        )}
        features.append({
            "type": feat_type,
            "start": start,
            "end": end,
            "strand": strand,
            "attrs": attrs,
        })

    return genome, features


def extract_seq(genome, start, end, strand):
    # GFF3 coords are 1-based inclusive; convert to 0-based for slicing
    seq = genome.seq[start - 1:end]
    if strand == "-":
        seq = seq.reverse_complement()
    return seq


def find_feature(features, name, feat_types=("gene", "CDS")):
    for f in features:
        if f["type"] in feat_types and f["attrs"].get("Name") == name:
            return f
    return None


def build_records(genome, features):
    records = []

    # 1) manB
    manB = find_feature(features, "manB")
    if manB is None:
        raise ValueError("manB gene not found in GFF3")
    seq1 = extract_seq(genome, manB["start"], manB["end"], manB["strand"])
    records.append(SeqRecord(
        seq1,
        id="manB",
        description=f"manB phosphomannomutase [{manB['start']}..{manB['end']} {manB['strand']}]",
    ))

    # 2) cpsG
    cpsG = find_feature(features, "cpsG")
    if cpsG is None:
        raise ValueError("cpsG not found in GFF3")
    seq2 = extract_seq(genome, cpsG["start"], cpsG["end"], cpsG["strand"])
    records.append(SeqRecord(
        seq2,
        id="cpsG",
        description=f"cpsG phosphomannomutase [{cpsG['start']}..{cpsG['end']} {cpsG['strand']}]",
    ))

    # 3) chimeric sequence from Δ23,293 bp deletion starting at position 2031703
    # Deletion removes 2031703..2054995, joining position 2031702 to 2054996.
    # On the minus strand: N-terminal portion comes from cpsG (2054996..2056096)
    # and C-terminal portion from manB (2031433..2031702).
    DELETION_START = 2031703
    DELETION_SIZE  = 23293
    DELETION_END   = DELETION_START + DELETION_SIZE - 1  # 2054995
    chimera_seg1 = extract_seq(genome, DELETION_END + 1, cpsG["end"], cpsG["strand"])
    chimera_seg2 = extract_seq(genome, manB["start"], DELETION_START - 1, manB["strand"])
    seq3 = chimera_seg1 + chimera_seg2
    records.append(SeqRecord(
        seq3,
        id="manB_cpsG_chimera",
        description=(
            f"chimeric sequence from delta{DELETION_SIZE} deletion at {DELETION_START}; "
            f"cpsG[{DELETION_END+1}..{cpsG['end']}]::manB[{manB['start']}..{DELETION_START-1}]"
        ),
    ))

    return records


def write_protein_fasta(dna_records, output_path):
    protein_records = []
    for rec in dna_records:
        protein_seq = rec.seq.translate()
        protein_records.append(SeqRecord(
            protein_seq,
            id=rec.id,
            description=rec.description,
        ))
    SeqIO.write(protein_records, output_path, "fasta")
    print(f"Wrote {len(protein_records)} protein sequences to {output_path}")
    for r in protein_records:
        print(f"  {r.id}: {len(r.seq)} aa")
    return protein_records


def _run_mafft(records, output_path, unit):
    with tempfile.NamedTemporaryFile(mode="w", suffix=".fasta", delete=False) as tmp:
        SeqIO.write(records, tmp, "fasta")
        tmp_path = Path(tmp.name)
    try:
        result = subprocess.run(
            ["mafft", "--auto", str(tmp_path)],
            capture_output=True,
            text=True,
            check=True,
        )
    finally:
        tmp_path.unlink()
    aligned = list(SeqIO.parse(io.StringIO(result.stdout), "fasta"))
    SeqIO.write(aligned, output_path, "fasta")
    print(f"Wrote alignment of {len(aligned)} sequences to {output_path}")
    for r in aligned:
        print(f"  {r.id}: {len(r.seq)} {unit}")


def align_proteins_with_mafft(protein_records, output_path):
    _run_mafft(protein_records, output_path, unit="aa")


def align_dna_with_mafft(dna_records, output_path):
    _run_mafft(dna_records, output_path, unit="bp")


def validate_outputs(dna_records, protein_records,
                     dna_aln_path, protein_aln_path):
    errors = []

    # Expected DNA lengths derived from the coordinate ranges in build_records
    expected_dna_lengths = {
        "manB":             2032797 - 2031433 + 1,   # 1365
        "cpsG":             2056096 - 2054726 + 1,   # 1371
        "manB_cpsG_chimera": (2056096 - 2054996 + 1) + (2031702 - 2031433 + 1),  # 1101 + 270 = 1371
    }

    dna_by_id     = {r.id: r for r in dna_records}
    protein_by_id = {r.id: r for r in protein_records}

    # 1. DNA record set matches expectation
    if set(dna_by_id) != set(expected_dna_lengths):
        errors.append(f"DNA record IDs {set(dna_by_id)} != expected {set(expected_dna_lengths)}")

    # 2. DNA lengths match coordinate-derived expectations
    for seq_id, exp_len in expected_dna_lengths.items():
        if seq_id not in dna_by_id:
            continue
        got = len(dna_by_id[seq_id].seq)
        if got != exp_len:
            errors.append(f"DNA '{seq_id}': expected {exp_len} bp, got {got} bp")

    # 3. Protein record IDs match DNA record IDs
    if set(protein_by_id) != set(dna_by_id):
        errors.append(f"Protein record IDs {set(protein_by_id)} != DNA IDs {set(dna_by_id)}")

    # 4. Protein length == DNA length / 3 for each record
    for seq_id in dna_by_id:
        if seq_id not in protein_by_id:
            continue
        dna_len     = len(dna_by_id[seq_id].seq)
        protein_len = len(protein_by_id[seq_id].seq)
        exp_protein_len = dna_len // 3
        if protein_len != exp_protein_len:
            errors.append(
                f"Protein '{seq_id}': expected {exp_protein_len} aa "
                f"(DNA {dna_len} bp / 3), got {protein_len} aa"
            )

    # 5. Protein sequences match in-memory translation of DNA
    for seq_id in dna_by_id:
        if seq_id not in protein_by_id:
            continue
        expected_aa = str(dna_by_id[seq_id].seq.translate())
        actual_aa   = str(protein_by_id[seq_id].seq)
        if expected_aa != actual_aa:
            errors.append(f"Protein '{seq_id}': sequence does not match DNA translation")

    # 6. Alignment files: record count, uniform length, degapped sequences match source
    # Match by position: FASTA headers with spaces are truncated on read-back by BioPython,
    # so id-based lookup is unreliable for the fusion sequence header.
    for aln_path, source_records_list, unit in [
        (protein_aln_path, protein_records, "aa"),
        (dna_aln_path,     dna_records,     "bp"),
    ]:
        aligned = list(SeqIO.parse(aln_path, "fasta"))
        if len(aligned) != len(source_records_list):
            errors.append(
                f"{aln_path}: expected {len(source_records_list)} sequences, got {len(aligned)}"
            )
            continue
        aln_lengths = {len(r.seq) for r in aligned}
        if len(aln_lengths) != 1:
            errors.append(f"{aln_path}: aligned sequences have unequal lengths {aln_lengths}")
        for aln_rec, src_rec in zip(aligned, source_records_list):
            degapped = str(aln_rec.seq).replace("-", "").rstrip("*").upper()
            expected = str(src_rec.seq).rstrip("*").upper()
            if degapped != expected:
                errors.append(
                    f"{aln_path} position {aligned.index(aln_rec)}: "
                    f"degapped aligned sequence does not match source"
                )

    if errors:
        for e in errors:
            print(f"  FAIL: {e}")
        raise AssertionError(f"{len(errors)} validation error(s) found")
    print("All validation checks passed.")


def main():
    GFF3_FILE = "../data/REL606.gff3"
    OUTPUT_FASTA = "../results/manB-cpsG_sequences.fasta"
    OUTPUT_PROTEIN_FASTA = "../results/manB-cpsG_sequences_protein.fasta"
    
    genome, features = parse_gff3_and_fasta(GFF3_FILE)
    records = build_records(genome, features)
    SeqIO.write(records, OUTPUT_FASTA, "fasta")

    OUTPUT_PROTEIN_ALN = "../results/manB-cpsG_sequences_protein_aligned.fasta"
    OUTPUT_DNA_ALN     = "../results/manB-cpsG_sequences_dna_aligned.fasta"
    
    protein_records = write_protein_fasta(records, OUTPUT_PROTEIN_FASTA)
    align_proteins_with_mafft(protein_records, OUTPUT_PROTEIN_ALN)
    align_dna_with_mafft(records, OUTPUT_DNA_ALN)
    validate_outputs(records, protein_records, OUTPUT_DNA_ALN, OUTPUT_PROTEIN_ALN)


if __name__ == "__main__":
    main()
